"""Initial migration

Revision ID: b930fd85e36c
Revises: 
Create Date: 2026-06-01 11:37:40.057915

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'b930fd85e36c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('categorias', schema=None) as batch_op:
        batch_op.alter_column('envia_a_cocina',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=False,
               existing_server_default=sa.text('0'))

    with op.batch_alter_table('mesas', schema=None) as batch_op:
        batch_op.alter_column('estado',
               existing_type=mysql.ENUM('disponible', 'ocupada'),
               nullable=False,
               existing_server_default=sa.text("'disponible'"))
        batch_op.create_foreign_key(None, 'mesas', ['grupo_mesa_id'], ['id'])

    with op.batch_alter_table('movimientos_caja', schema=None) as batch_op:
        batch_op.alter_column('created_at',
               existing_type=mysql.TIMESTAMP(),
               type_=sa.DateTime(),
               existing_nullable=False,
               existing_server_default=sa.text('current_timestamp()'))

    with op.batch_alter_table('movimientos_inventario', schema=None) as batch_op:
        batch_op.alter_column('created_at',
               existing_type=mysql.TIMESTAMP(),
               type_=sa.DateTime(),
               existing_nullable=False,
               existing_server_default=sa.text('current_timestamp()'))
        batch_op.drop_index(batch_op.f('idx_mov_inv_producto'))
        batch_op.create_foreign_key(None, 'productos', ['producto_destino_id'], ['id'])

    with op.batch_alter_table('orden_division_items', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('idx_orden_division_items_division'))
        batch_op.drop_index(batch_op.f('idx_orden_division_items_item'))

    with op.batch_alter_table('orden_divisiones', schema=None) as batch_op:
        batch_op.alter_column('pagada',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=False,
               existing_server_default=sa.text('0'))
        batch_op.alter_column('created_at',
               existing_type=mysql.TIMESTAMP(),
               type_=sa.DateTime(),
               existing_nullable=False,
               existing_server_default=sa.text('current_timestamp()'))
        batch_op.drop_index(batch_op.f('idx_orden_divisiones_orden'))

    with op.batch_alter_table('orden_items', schema=None) as batch_op:
        batch_op.alter_column('costo_unitario',
               existing_type=mysql.DECIMAL(precision=10, scale=2),
               nullable=False,
               existing_server_default=sa.text('0.00'))
        batch_op.alter_column('estado',
               existing_type=mysql.ENUM('pendiente', 'listo', 'entregado', 'cancelado'),
               nullable=False,
               existing_server_default=sa.text("'pendiente'"))
        batch_op.alter_column('pagado',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=False,
               existing_server_default=sa.text('0'))
        batch_op.alter_column('created_at',
               existing_type=mysql.TIMESTAMP(),
               type_=sa.DateTime(),
               existing_nullable=False,
               existing_server_default=sa.text('current_timestamp()'))
        batch_op.drop_index(batch_op.f('idx_orden_items_orden'))
        batch_op.drop_index(batch_op.f('idx_orden_items_producto'))

    with op.batch_alter_table('ordenes', schema=None) as batch_op:
        batch_op.alter_column('total',
               existing_type=mysql.DECIMAL(precision=10, scale=2),
               nullable=False,
               existing_server_default=sa.text('0.00'))
        batch_op.alter_column('estado',
               existing_type=mysql.ENUM('abierta', 'pagada', 'cancelada'),
               nullable=False,
               existing_server_default=sa.text("'abierta'"))
        batch_op.alter_column('created_at',
               existing_type=mysql.TIMESTAMP(),
               type_=sa.DateTime(),
               existing_nullable=False,
               existing_server_default=sa.text('current_timestamp()'))

    with op.batch_alter_table('pagos', schema=None) as batch_op:
        batch_op.alter_column('created_at',
               existing_type=mysql.TIMESTAMP(),
               type_=sa.DateTime(),
               existing_nullable=False,
               existing_server_default=sa.text('current_timestamp()'))

    with op.batch_alter_table('productos', schema=None) as batch_op:
        batch_op.alter_column('precio_costo',
               existing_type=mysql.DECIMAL(precision=10, scale=2),
               nullable=False,
               existing_server_default=sa.text('0.00'))
        batch_op.alter_column('unidad_compra',
               existing_type=mysql.VARCHAR(length=30),
               nullable=False,
               existing_server_default=sa.text("'unidad'"))
        batch_op.alter_column('unidades_por_paquete',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False,
               existing_server_default=sa.text('1'))
        batch_op.alter_column('stock_actual',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False,
               existing_server_default=sa.text('0'))
        batch_op.alter_column('maneja_stock',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=False,
               existing_server_default=sa.text('1'))
        batch_op.alter_column('disponible',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=False,
               existing_server_default=sa.text('1'))
        batch_op.create_foreign_key(None, 'productos', ['producto_inventario_id'], ['id'])

    with op.batch_alter_table('sesiones_caja', schema=None) as batch_op:
        batch_op.alter_column('fecha_apertura',
               existing_type=mysql.TIMESTAMP(),
               type_=sa.DateTime(),
               existing_nullable=False,
               existing_server_default=sa.text('current_timestamp()'))
        batch_op.alter_column('fecha_cierre',
               existing_type=mysql.TIMESTAMP(),
               type_=sa.DateTime(),
               existing_nullable=True)
        batch_op.alter_column('estado',
               existing_type=mysql.ENUM('abierta', 'cerrada'),
               nullable=False,
               existing_server_default=sa.text("'abierta'"))

    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.alter_column('rol',
               existing_type=mysql.ENUM('dueño', 'cajero', 'mesero', 'cocina'),
               type_=sa.String(length=30),
               existing_nullable=False)
        batch_op.alter_column('activo',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=False,
               existing_server_default=sa.text('1'))
        batch_op.alter_column('created_at',
               existing_type=mysql.TIMESTAMP(),
               type_=sa.DateTime(),
               existing_nullable=False,
               existing_server_default=sa.text('current_timestamp()'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.alter_column('created_at',
               existing_type=sa.DateTime(),
               type_=mysql.TIMESTAMP(),
               existing_nullable=False,
               existing_server_default=sa.text('current_timestamp()'))
        batch_op.alter_column('activo',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=True,
               existing_server_default=sa.text('1'))
        batch_op.alter_column('rol',
               existing_type=sa.String(length=30),
               type_=mysql.ENUM('dueño', 'cajero', 'mesero', 'cocina'),
               existing_nullable=False)

    with op.batch_alter_table('sesiones_caja', schema=None) as batch_op:
        batch_op.alter_column('estado',
               existing_type=mysql.ENUM('abierta', 'cerrada'),
               nullable=True,
               existing_server_default=sa.text("'abierta'"))
        batch_op.alter_column('fecha_cierre',
               existing_type=sa.DateTime(),
               type_=mysql.TIMESTAMP(),
               existing_nullable=True)
        batch_op.alter_column('fecha_apertura',
               existing_type=sa.DateTime(),
               type_=mysql.TIMESTAMP(),
               existing_nullable=False,
               existing_server_default=sa.text('current_timestamp()'))

    with op.batch_alter_table('productos', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.alter_column('disponible',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=True,
               existing_server_default=sa.text('1'))
        batch_op.alter_column('maneja_stock',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=True,
               existing_server_default=sa.text('1'))
        batch_op.alter_column('stock_actual',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True,
               existing_server_default=sa.text('0'))
        batch_op.alter_column('unidades_por_paquete',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True,
               existing_server_default=sa.text('1'))
        batch_op.alter_column('unidad_compra',
               existing_type=mysql.VARCHAR(length=30),
               nullable=True,
               existing_server_default=sa.text("'unidad'"))
        batch_op.alter_column('precio_costo',
               existing_type=mysql.DECIMAL(precision=10, scale=2),
               nullable=True,
               existing_server_default=sa.text('0.00'))

    with op.batch_alter_table('pagos', schema=None) as batch_op:
        batch_op.alter_column('created_at',
               existing_type=sa.DateTime(),
               type_=mysql.TIMESTAMP(),
               existing_nullable=False,
               existing_server_default=sa.text('current_timestamp()'))

    with op.batch_alter_table('ordenes', schema=None) as batch_op:
        batch_op.alter_column('created_at',
               existing_type=sa.DateTime(),
               type_=mysql.TIMESTAMP(),
               existing_nullable=False,
               existing_server_default=sa.text('current_timestamp()'))
        batch_op.alter_column('estado',
               existing_type=mysql.ENUM('abierta', 'pagada', 'cancelada'),
               nullable=True,
               existing_server_default=sa.text("'abierta'"))
        batch_op.alter_column('total',
               existing_type=mysql.DECIMAL(precision=10, scale=2),
               nullable=True,
               existing_server_default=sa.text('0.00'))

    with op.batch_alter_table('orden_items', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('idx_orden_items_producto'), ['producto_id'], unique=False)
        batch_op.create_index(batch_op.f('idx_orden_items_orden'), ['orden_id'], unique=False)
        batch_op.alter_column('created_at',
               existing_type=sa.DateTime(),
               type_=mysql.TIMESTAMP(),
               existing_nullable=False,
               existing_server_default=sa.text('current_timestamp()'))
        batch_op.alter_column('pagado',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=True,
               existing_server_default=sa.text('0'))
        batch_op.alter_column('estado',
               existing_type=mysql.ENUM('pendiente', 'listo', 'entregado', 'cancelado'),
               nullable=True,
               existing_server_default=sa.text("'pendiente'"))
        batch_op.alter_column('costo_unitario',
               existing_type=mysql.DECIMAL(precision=10, scale=2),
               nullable=True,
               existing_server_default=sa.text('0.00'))

    with op.batch_alter_table('orden_divisiones', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('idx_orden_divisiones_orden'), ['orden_id'], unique=False)
        batch_op.alter_column('created_at',
               existing_type=sa.DateTime(),
               type_=mysql.TIMESTAMP(),
               existing_nullable=False,
               existing_server_default=sa.text('current_timestamp()'))
        batch_op.alter_column('pagada',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=True,
               existing_server_default=sa.text('0'))

    with op.batch_alter_table('orden_division_items', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('idx_orden_division_items_item'), ['orden_item_id'], unique=False)
        batch_op.create_index(batch_op.f('idx_orden_division_items_division'), ['division_id'], unique=False)

    with op.batch_alter_table('movimientos_inventario', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_index(batch_op.f('idx_mov_inv_producto'), ['producto_id'], unique=False)
        batch_op.alter_column('created_at',
               existing_type=sa.DateTime(),
               type_=mysql.TIMESTAMP(),
               existing_nullable=False,
               existing_server_default=sa.text('current_timestamp()'))

    with op.batch_alter_table('movimientos_caja', schema=None) as batch_op:
        batch_op.alter_column('created_at',
               existing_type=sa.DateTime(),
               type_=mysql.TIMESTAMP(),
               existing_nullable=False,
               existing_server_default=sa.text('current_timestamp()'))

    with op.batch_alter_table('mesas', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.alter_column('estado',
               existing_type=mysql.ENUM('disponible', 'ocupada'),
               nullable=True,
               existing_server_default=sa.text("'disponible'"))

    with op.batch_alter_table('categorias', schema=None) as batch_op:
        batch_op.alter_column('envia_a_cocina',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=True,
               existing_server_default=sa.text('0'))

    # ### end Alembic commands ###
